# Generated by Django 4.0.1 on 2024-09-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_nm',
            field=models.IntegerField(blank=True, default=0, max_length=8, verbose_name=''),
        ),
    ]
