# Generated by Django 4.0.1 on 2024-09-30 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_nm',
        ),
    ]
