# Generated by Django 4.0.1 on 2024-09-25 09:26

import api.on_lib.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('on_lib', '0003_book_owner_book_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='name')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid_author')),
                ('last_name', models.CharField(max_length=40, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='email')),
            ],
            options={
                'db_table': 'onlib_author',
            },
        ),
        migrations.CreateModel(
            name='Book_project_lib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lib', models.CharField(max_length=20)),
                ('description', models.TextField(verbose_name='description_lib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onlib_bookfile',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('file_name', models.CharField(max_length=100)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to=api.on_lib.models.upload_file_path_handler, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'txt', 'xls', 'xlsx', 'ods', 'doc', 'odt', 'ppt', 'pptx']), api.on_lib.models.validator_file_size], verbose_name='upload_file')),
                ('file_ext', models.CharField(max_length=5, verbose_name='extention')),
                ('file_sz', models.FloatField(default=0, verbose_name='file size')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='file_created')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='file_updated')),
                ('genre', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('file_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='on_lib.book_project_lib')),
            ],
            options={
                'db_table': 'onlib_file',
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='authors',
            name='author_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='on_lib.file'),
        ),
    ]
