# Generated by Django 4.0.1 on 2024-09-26 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('on_lib', '0006_alter_book_project_lib_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='', max_length=20, verbose_name='library name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description_lib')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='cat')),
                ('quantity', models.IntegerField(default=0, verbose_name='qnt')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quality_check', models.CharField(max_length=50, verbose_name='qualty')),
                ('logistic_details', models.CharField(max_length=50, verbose_name='log')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create at ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onlib_bookfile',
            },
        ),
        migrations.AlterField(
            model_name='file',
            name='file_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='on_lib.product'),
        ),
        migrations.DeleteModel(
            name='Book_project_lib',
        ),
    ]
