# Generated by Django 4.0.1 on 2024-09-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('on_lib', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrow',
        ),
    ]
