# Generated by Django 4.0.1 on 2024-09-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_lib', '0004_authors_book_project_lib_file_delete_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_project_lib',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create at '),
        ),
        migrations.AlterField(
            model_name='book_project_lib',
            name='name_lib',
            field=models.CharField(max_length=20, verbose_name='library name'),
        ),
    ]
