# Generated by Django 4.0.1 on 2024-09-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_lib', '0005_alter_book_project_lib_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_project_lib',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description_lib'),
        ),
        migrations.AlterField(
            model_name='book_project_lib',
            name='name_lib',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='library name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_ext',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='extention'),
        ),
        migrations.AlterField(
            model_name='file',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
