# Generated by Django 4.0.1 on 2024-09-29 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('transportMode', models.CharField(choices=[('post', 'post'), ('car', 'car')], default='car', max_length=40, verbose_name='transportM')),
                ('deliveryStatus', models.CharField(choices=[('idle', 'idle'), ('pending', 'pending'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='idle', max_length=40, verbose_name='deliveryStatus')),
                ('shippingDetails', models.CharField(max_length=50, verbose_name='shippingDetails')),
            ],
            options={
                'db_table': 'logistic_table',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='', max_length=20, verbose_name='library name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description_lib')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='cat')),
                ('quantity', models.IntegerField(default=0, verbose_name='qnt')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create at ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
            ],
            options={
                'db_table': 'product_table',
            },
        ),
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('location', models.CharField(choices=[('Tunis', 'Tunis'), ('Medjaz_El_Bab', 'Medjaz_El_Bab')], default='Medjaz_El_Bab', max_length=40, verbose_name='loca_tion')),
                ('date', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'db_table': 'rdv_table',
            },
        ),
    ]
