# Generated by Django 4.0.1 on 2025-01-24 15:02

import api.gr.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name_mk')),
                ('mark_number', models.CharField(choices=[('product_one', 'product_one'), ('product_two', 'product_two'), ('product_three', 'product_three'), ('product_four', 'product_four')], default='product_one', max_length=50)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
            ],
            options={
                'verbose_name': 'Market _table',
                'verbose_name_plural': 'Market _tables',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='order date')),
                ('status', models.CharField(choices=[(api.gr.models.Status['IDLE'], 'idle'), (api.gr.models.Status['PENDING'], 'pending'), (api.gr.models.Status['DELIVERED'], 'delivered'), (api.gr.models.Status['CANCELED'], 'canceled')], default='idle', max_length=20, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='qnt')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='', max_length=20, verbose_name='library name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description_lib')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create at ')),
                ('stock', models.IntegerField(default=0, verbose_name='stock')),
                ('type', models.CharField(choices=[('muli pack prd', 'muli pack prd'), ('Single Product', 'Single Product')], default='Single Product', max_length=20, verbose_name='Type of product')),
                ('rating', models.FloatField(blank=True, choices=[(0.0, 0.0), (1.0, 1.0), (2.0, 2.0), (3.0, 3.0), (4.0, 4.0), (5.0, 5.0)], default=0.0, verbose_name=' rating of  product')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('Buy_sell', models.CharField(choices=[('buyer', 'buyer'), ('seller', 'seller')], default='buyer', max_length=10, verbose_name='buyer seller')),
            ],
            options={
                'verbose_name': 'product_table',
                'verbose_name_plural': 'product_tables',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, choices=[(api.gr.models.Payment_type['CASH'], 'cash'), (api.gr.models.Payment_type['RIP'], 'Rip')], default='cash', max_length=20, verbose_name='payment method')),
                ('singel_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('group_amount', models.DecimalField(choices=[(api.gr.models.Opt_Prod['GROUP_PROD'], 'Group product')], decimal_places=2, default=1, max_digits=10)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gr.order')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
    ]
