# Generated by Django 4.0.1 on 2025-01-24 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='stock_k',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gr.product'),
        ),
        migrations.AddField(
            model_name='order_item',
            name='item_K',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gr.order'),
        ),
        migrations.AddField(
            model_name='order_item',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gr.product'),
        ),
    ]
